### ISSUE TITLE
call init_environment after downloading the sandbox

### ISSUE THREAD

**Issue by guskovd** [saltstack/kitchen-salt#206]
to prepare the environment, I would like to have a set of scripts, the salt-master key, loaded through the data_path.

**Comment by gtmanfred** [comment]
I would say the best way to do this is use this option

https://kitchen.saltstack.com/docs/file/docs/provisioner_options.md#install_after_init_environment

And then the bootstrap script can be run afterwards init_environment.  This is what is used in order to make the an sdist available inside the test instance, so that the current version of saltstack that is being tested can be run inside the container for these tests https://github.com/saltstack/salt/tree/oxygen/tests/kitchen

And you can use a custom bootstrap script,  just pass the relative path to the bootstrap script into https://kitchen.saltstack.com/docs/file/docs/provisioner_options.md#salt_bootstrap_url

**Comment by guskovd** [comment]
https://kitchen.saltstack.com/docs/file/docs/provisioner_options.md#install_after_init_environment
does not solve this problem in any way.

For example, I run converge for the first time. At the time of this command, the kitchen folder on the remote machine is empty

**Comment by gtmanfred** [comment]
You will have to set that to True, and then write a custom bootstrap script instead of using init_environment.

There is nothing that kitchen-salt can do about that.

The base provisioner runs the init_command before it uploads the sandbox.

https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/base.rb#L72

**Comment by guskovd** [comment]
Why should init_environment necessarily be called from init_command?
Here's my solution: https://github.com/guskovd/kitchen-salt/commit/f3d4b24a9716076eca9a2b18537099057357ff54
in .kitchen.yml
```yaml
provisioner:
  pre_salt_call_hook: '/tmp/kichen/data/my-awesome-script.sh'
```

**Comment by gtmanfred** [comment]
It wasn't that it should be called from init_command, it was that it was called from there, and moving it could break other peoples setups.

Can you move it to the `prepare_command` instead of the `salt_command` and also rename it `prepare_salt_environment`?

Thanks,
Daniel

**Comment by guskovd** [comment]
of course, I will do tomorrow

**Comment by gtmanfred** [comment]
Perfect, I am out of the office tomorrow, but I will take a look monday!

Thanks!
Daniel

**Comment by guskovd** [comment]
my pull request:
https://github.com/saltstack/kitchen-salt/pull/207

**Comment by gtmanfred** [comment]
Merged
