### ISSUE TITLE
testinfra support?

### ISSUE THREAD

**Issue by simonmcc** [saltstack/kitchen-salt#24]
Testinfra is a tool for writing unit tests for infrastructure, similar to Serverspec but implemented in Python. It supports a few standard privatives like files, services, packages and users, as well as featuring integration with Salt and Puppet.

https://github.com/philpep/testinfra
http://testinfra.readthedocs.org/en/latest/

**Comment by doertedev** [comment]
:+1:

**Comment by cmarzullo** [comment]
Worth noting: https://github.com/ssplatt/saltstack-infratest-module

**Comment by syndicut** [comment]
If you are interested I've done this with shell_verifier: https://medium.com/@syndicut/testing-salt-formulas-with-test-kitchen-and-testinfra-d2b8642e6a39
This is an example setup: https://github.com/syndicut/mongodb-formula/tree/testinfra-testing

**Comment by blbradley** [comment]
Test Kitchen [recommends](https://github.com/test-kitchen/busser-serverspec#-notice) the shell verifier & serverspec instead of busser-serverspec now. Something similar works for the shell verifier & testinfra as shown by @syndicut. 

I'd close this unless you want to add a note about the shell verifier & testinfra.

@syndicut Thanks for your blog bost! It was invaluable to adding testing to [docker-formula](https://github.com/saltstack-formulas/docker-formula).

**Comment by gtmanfred** [comment]
I am going to go ahead and close this since test-kitchen recommends using the shell verifier anyway.

Thanks,
Daniel
