### ISSUE TITLE
All states and pillars are copied in TMPDIR

### ISSUE THREAD

**Issue by daks** [saltstack/kitchen-salt#97]
Hello,

When kitchen-salt converges, there is a step of files transfers to copy them to /tmp/kitchen inside the VM.
But it seems that it's done in two steps:

- first: copy all sources to TMPDIR (/tmp by default)
- second: make them available inside the VM (sometimes it's a copy but it can be just mounting the temp dir with data inside the VM)

In our case, we use kitchen to test a full repository of salt states/pillars and files, which is several hundreds of MB. This double copy slows down our testing.

I wonder if the data directory could be directly shared/copied inside the VM, without this extra step.

I'm not sure this comes from kitchen-salt or test-kitchen.

**Comment by gtmanfred** [comment]
This seems reasonable, but I am also not sure which library does this.  I have a suspicion that it is test-kitchen and that we just use the test-kitchen library to put the files on the vm.  But will try and look closer.

Thanks for the request.
Daniel

**Comment by gtmanfred** [comment]
I have gotten more involved in test-kitchen, and know how more of it works.

Have you tried looking at using `kitchen-sync` to speed up the copying? 

https://github.com/coderanger/kitchen-sync

The `sftp` transport also uses a helper script to copy the files over.

If you are wanting to not copy the files to /tmp on your local box, you will need to open a bug with test-kitchen, because that is how provisioners are supposed to work.  the provisioner just copies the files to it's defined `sandbox_path` and then test-kitchen uses the transport layer to upload them to the vm's root path, which defaults to `/tmp/kitchen`

So there isn't a lot that we can do from a provisioner aspect, the underlying technology would need to change to allow you to not have to copy the files over.  Potentially we could change to using symlinks instead of copying, but there is not a symlink function similar to `FileUtils.cp_r` that test-kitchen currently provides.

Thanks,
Daniel
